# Generated by Django 5.2.16 on 2026-07-20 14:47

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


NICKNAMES = [
    "행복한 클로디", "신나는 마니", "다정한 클로디", "포근한 마니", "반짝이는 클로디", "용감한 마니",
    "설레는 클로디", "웃는 마니", "달콤한 클로디", "부지런한 마니", "호기심 많은 클로디", "따뜻한 마니",
    "장난꾸러기 클로디", "빛나는 마니", "느긋한 클로디", "응원하는 마니", "몽글몽글 클로디", "선물 든 마니",
    "별빛 클로디", "수줍은 마니", "꿈꾸는 클로디", "힘찬 마니", "산뜻한 클로디", "도토리 마니",
    "하늘빛 클로디", "반가운 마니", "씩씩한 클로디", "마음 따뜻한 마니", "구름 위 클로디", "행복 배달 마니",
]
AVATAR_KEYS = [*(f"mani-{index}" for index in range(9)), *(f"clodi-{index}" for index in range(9))]


def assign_existing_profiles(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Participant = apps.get_model("teams", "Participant")
    LeaderboardSnapshot = apps.get_model("teams", "LeaderboardSnapshot")
    pairs = [(nickname, avatar_key) for nickname in NICKNAMES for avatar_key in AVATAR_KEYS]
    now = timezone.now()
    for team in Team.objects.all().order_by("created_at", "id"):
        participants = list(Participant.objects.filter(team_id=team.id).order_by("created_at", "id"))
        rankings = []
        for index, participant in enumerate(participants):
            nickname, avatar_key = pairs[index % len(pairs)]
            participant.leaderboard_nickname = nickname
            participant.leaderboard_avatar_key = avatar_key
            participant.save(update_fields=["leaderboard_nickname", "leaderboard_avatar_key"])
            if index < 123:
                rankings.append({"participant_id": participant.id, "rank": 1})
        LeaderboardSnapshot.objects.create(team_id=team.id, rankings=rankings, generated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_notification_team_announcement'),
        ('teams', '0006_remove_team_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_visit_score_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='leaderboard_avatar_key',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='leaderboard_nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='leaderboard_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankings', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshot', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHAT_MESSAGE', '채팅 전송'), ('CHAT_LIKE', '좋아요'), ('TEAM_VISIT', '팀 접속')], max_length=20)),
                ('room_id', models.CharField(blank=True, max_length=50)),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='teams.participant')),
                ('source_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_event', to='chat.message')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='teams.team')),
            ],
        ),
        migrations.RunPython(assign_existing_profiles, migrations.RunPython.noop),
    ]
