# Generated by Django 5.2.16 on 2026-08-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_notification_dedupe_key_alter_notification_kind'),
        ('quizzes', '0001_initial'),
        ('teams', '0010_service_access_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreevent',
            name='quiz_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='quizzes.quizitem'),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='requested_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='event_type',
            field=models.CharField(choices=[('CHAT_MESSAGE', '채팅 전송'), ('CHAT_LIKE', '좋아요'), ('TEAM_VISIT', '팀 접속 (이전 정책)'), ('SERVICE_ACCESS', '서비스 접속'), ('QUIZ_SOLVER_RESULT', '퀴즈 풀이 결과'), ('QUIZ_AUTHOR_ADJUSTMENT', '퀴즈 작성자 보상·감점')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_item__isnull', False)), fields=('quiz_item', 'event_type'), name='unique_quiz_score_event_role'),
        ),
    ]
