# Generated by Django 5.2.16 on 2026-08-02 12:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0010_service_access_scoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=30, unique=True)),
                ('original_number', models.PositiveIntegerField(unique=True)),
                ('category', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', '진행 중'), ('SETTLED', '정산 완료'), ('CANCELLED', '취소')], default='ACTIVE', max_length=12)),
                ('collision_decision', models.CharField(choices=[('NOT_REQUIRED', '결정 불필요'), ('PENDING', '결정 대기'), ('PROCEED', '진행'), ('CANCEL', '취소')], default='NOT_REQUIRED', max_length=20)),
                ('collision_decided_at', models.DateTimeField(blank=True, null=True)),
                ('question_mode', models.CharField(choices=[('SYSTEM', '랜덤 퀴즈'), ('COMMON', '공통 퀴즈')], max_length=10)),
                ('common_question_snapshot', models.TextField(blank=True)),
                ('quiz_timezone', models.CharField(max_length=64)),
                ('reference_days', models.PositiveSmallIntegerField()),
                ('solve_days', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('reference_ends_at', models.DateTimeField(db_index=True)),
                ('solve_ends_at', models.DateTimeField(db_index=True)),
                ('evaluation_ends_at', models.DateTimeField(db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collision_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_quiz_rounds', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_rounds', to='teams.team')),
            ],
            options={
                'ordering': ['team_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_kind', models.CharField(choices=[('SYSTEM', '랜덤 퀴즈'), ('COMMON', '공통 퀴즈')], max_length=10)),
                ('question_key', models.CharField(max_length=300)),
                ('question_normalized', models.TextField()),
                ('question_snapshot', models.TextField()),
                ('reference_answer', models.TextField(blank=True)),
                ('reference_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('solution_draft', models.TextField(blank=True)),
                ('solution_draft_saved_at', models.DateTimeField(blank=True, null=True)),
                ('solution_submitted', models.TextField(blank=True)),
                ('solution_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_kind', models.CharField(blank=True, choices=[('REFERENCE_MISSING', '기준 답안 미입력'), ('SOLUTION_MISSING', '풀이 답안 미제출'), ('EVALUATED', '정상 평가'), ('EVALUATION_MISSING', '평가 미완료')], max_length=30)),
                ('raw_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_max_score', models.PositiveSmallIntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_quiz_items', to='teams.participant')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_quiz_items', to='teams.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.quizround')),
                ('system_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_items', to='quizzes.systemquizquestion')),
            ],
            options={
                'ordering': ['round_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamQuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('quiz_timezone', models.CharField(blank=True, max_length=64)),
                ('reference_days', models.PositiveSmallIntegerField(default=2)),
                ('solve_days', models.PositiveSmallIntegerField(default=3)),
                ('next_round_starts_at', models.DateTimeField(blank=True, null=True)),
                ('next_common_question', models.TextField(blank=True)),
                ('next_common_question_normalized', models.TextField(blank=True)),
                ('all_claimed_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_settings', to='teams.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizround',
            constraint=models.UniqueConstraint(fields=('team', 'sequence'), name='unique_quiz_round_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quizround',
            constraint=models.UniqueConstraint(fields=('team', 'starts_at'), name='unique_quiz_round_start'),
        ),
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.UniqueConstraint(fields=('round', 'author'), name='unique_quiz_author_per_round'),
        ),
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.UniqueConstraint(fields=('round', 'solver'), name='unique_quiz_solver_per_round'),
        ),
        migrations.AddConstraint(
            model_name='quizitem',
            constraint=models.CheckConstraint(condition=models.Q(('evaluation_score__isnull', True), models.Q(('evaluation_score__gte', 1), ('evaluation_score__lte', 5)), _connector='OR'), name='quiz_evaluation_score_between_1_and_5'),
        ),
    ]
