# Generated by Django 5.2.16 on 2026-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizround_evaluation_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='solve_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
