# Generated by Django 5.2.4 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_webpushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_platform",
            field=models.CharField(
                choices=[("ANDROID", "Android"), ("IOS", "iOS")],
                default="ANDROID",
                help_text="기기 알림 발송 방식",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="IOSWebPushSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.URLField(max_length=2048, unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ios_web_push_subscriptions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
