# Generated by Django 5.2.4 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_notification_platform_ioswebpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kakao_notification_enabled",
            field=models.BooleanField(default=True, help_text="카카오톡 나와의 채팅 알림 수신 여부"),
        ),
    ]
