# Generated by Django 5.2.4 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_feedbackthread_feedbackmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackmessage",
            name="emoticon_key",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="feedbackmessage",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="FeedbackMessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="feedback_chat/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="chat.feedbackmessage")),
            ],
        ),
    ]
