# Generated by Django 5.2.16 on 2026-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_generalize_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('MESSAGE', '새 메시지'), ('FEEDBACK_MESSAGE', '새 개발자 피드백'), ('COUNTERPART_CLAIMED', '상대방 확인 완료'), ('PARTICIPANT_CLAIMED', '참여자 확인 완료'), ('DDAY', 'D-Day'), ('RESULT_AVAILABLE', '결과 공개'), ('TEAM_ANNOUNCEMENT', '팀 공지'), ('QUIZ_READY', '퀴즈 활성화 가능'), ('QUIZ_REFERENCE_OPEN', '기준 답안 입력'), ('QUIZ_SOLVE_OPEN', '퀴즈 풀이'), ('QUIZ_EVALUATION_OPEN', '퀴즈 평가'), ('QUIZ_END_CONFLICT', '종료 예정일 충돌'), ('QUIZ_POOL_EXHAUSTED', '질문 풀 소진'), ('QUIZ_ROUND_CANCELLED', '퀴즈 회차 취소')], max_length=30),
        ),
    ]
